### ISSUE TITLE
Does this work on macos

### ISSUE THREAD

**Issue by Cheesonator112** [ofarrelle/dualshock-joystick#1]

**Comment by ofarrelle** [comment]
I'm not sure, I don't have a Mac to test this with. But I would invite you to give it a shot!

If you can figure out how to connect the Dualshock controller and find the program files associated with the flight simulator, I assume the [dualshock_4.ini](https://github.com/ofarrelle/dualshock-joystick/blob/master/dualshock_4.ini) file should still work.
Let me know how it goes.

**Comment by Cheesonator112** [comment]
yh, it works fine thankyou, just had to find the right folder because it uses a different file system

**Comment by ofarrelle** [comment]
Fantastic! Happy to help.
In case anyone else tries this in the future, what file path did you have to follow?
